server:
  port: 8102
  servlet:
    context-path: /client1

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: clientapp
      client-secret: 112233
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://www.server.com:8101/server/oauth/check_token # 获得 Token 信息的 URL
    # 访问令牌获取 URL，自定义的
    access-token-uri: http://www.server.com:8101/server/oauth/token
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          clientapp:
#            client-id: clientapp
#            client-secret: 112233
#
#        provider:
#          clientapp:
#            tokenUri: http://127.0.0.1:8101/oauth/check_token

