server:
  port: 8102
  servlet:
    context-path: /client1
security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: clientapp
      client-secret: 112233
      user-authorization-uri: http://www.server.com:8101/server/oauth/authorize # 获取用户的授权码地址
      access-token-uri: http://www.server.com:8101/server/oauth/token # 获取访问令牌的地址
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://www.server.com:8101/server/oauth/check_token # 获得 Token 信息的 URL
    # 访问令牌获取 URL，自定义的
    access-token-uri: http://www.server.com:8101/server/oauth/token
